### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by Blakeinstein** [Blakeinstein/Bloop#3]
Just saw https://github.com/MGlolenstine/Bloop .

Would there be interest in a linux version aswell? I am looking to add the missing methods, to the webview crate and using that instead of a custom fork.

@MGolenstine

**Comment by MGlolenstine** [comment]
There would be interest. I'm using it on a daily basis and (because I use tiling WM) don't really need the missing features.
If there's a way to add those methods, I'm all in for it!

I can make a pull request, if that's needed.
(there was some reformatting and two scripts added, with which I had some difficulty as there was no documentation written yet, so I'd add them for clarity.).
@Blakeinstein 
(Also, sorry for late response, I  didn't get tagged (notified) and I just noticed one issue and was wondering what it was.)

**Comment by Blakeinstein** [comment]
Ah I would definitely write documentation! And as far as linux support goes, I will just implement the same for linux on the webview framework this is based on!

Also sorry if I was rude by missing an L, I totally didnt notice.

**Comment by MGlolenstine** [comment]
Not rude at all! Thanks for tagging me!

I'd really love to see linux support for your fork of the library.

**Comment by Blakeinstein** [comment]
Currently I am working on frameless fixes for windows version of webview. I will add linux support soon. 
Could you list the current missing features? 
I believe you cant drag window yet on linux.

**Comment by MGlolenstine** [comment]
I'm not sure, but I know that features that I commented in the `main.rs` are the ones that didn't work for me on Linux. I can check it more thoroughly tomorrow.

**Comment by Blakeinstein** [comment]
Ah those dont have bindings present in the webview. Just check out how the window frame behaves.

**Comment by Blakeinstein** [comment]
@MGlolenstine I just saw you add scripts to the scripts folder... you can just copy scripts to `/home/alice/Documents/bloop`

also you can source an additional hoard of scripts from http://github.com/ivanmathy/boop
check the directory, `boop/Boop/Boop/scripts`

My CI script clones that repo and copies it over to `src/scripts` and then builds. This avoids me having to sync scripts over.

**Comment by MGlolenstine** [comment]
I tried porting most of those plugins but had problems when starting the application (Something about missing scripts).

I have no idea about Webview2GTK, as I've never worked with it on Windows.

**Comment by Blakeinstein** [comment]
Its a linux requirement for webview-rs. Part of gtk3 I think. Required to build the project on linux. 


Also I think the error you are having is due to a trailling `,` in the metadata of the script. There should be one in two files, if you are using the ones from the root scripts folder. i.e https://github.com/IvanMathy/Boop/blob/main/Scripts

The files are 
> TrimStart.js
```js
		"icon":"scissors",
		"tags":"trim,start,left,leading,beginning,whitespace,empty,space",  <--- trailing comma
	}
**/
```

> TrimEnd.js
```js
		"icon":"scissors",
		"tags":"trim,end,right,trailing,whitespace,empty,space",   <--- trailing comma
	}
**/
```

This is invalid json behaviour

Try the ones here https://github.com/IvanMathy/Boop/tree/main/Boop/Boop/scripts , you can use [this](https://download-directory.github.io/?url=https%3A%2F%2Fgithub.com%2FIvanMathy%2FBoop%2Ftree%2Fmain%2FBoop%2FBoop%2Fscripts) to download the directory.

**Comment by MGlolenstine** [comment]
I was indeed using the latter ones but got some weird popups as I mentioned before.

You are indeed correct, `webkit2gtk` can be found on AUR [`webkit2gtk`](https://aur.archlinux.org/packages/webkit2gtk-unstable/) (I'm using Arch, btw).

**Comment by Blakeinstein** [comment]
> Some weird popups, as I mentioned before.
> 

Most likely errors on parsing the meta, the tool uses serde-json and treats the meta as a json string. Any scripts that error out, would be skipped and the error would be printed out in a tinyfiledialog.

I only considered for wrong meta, but seems like I might have missed out a few cases, resulting in nothing being printed.

I will start testing on my vm I guess. Errored out with missing Cairo, on WSL.
